USE Test1;
    ALTER TABLE TestTable_01 DROP ProductId;
    ALTER TABLE TestTable_01 ADD ProductId INT NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY(ProductId);
    ALTER TABLE TestTable_01 AUTO_INCREMENT=1;